---
name: Auto-merge Dependabot PRs

"on":
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug actor information
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Event name: ${{ github.event_name }}"
          echo "PR author: ${{ github.event.pull_request.user.login }}"
          echo "PR author type: ${{ github.event.pull_request.user.type }}"

  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}

      - name: Enable auto-merge for Dependabot PRs
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            try {
              await github.rest.pulls.enableAutoMerge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                merge_method: 'squash'
              });

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: '🤖 Auto-merge enabled. This PR will merge automatically once all required checks pass.'
              });

              console.log('Auto-merge enabled successfully');
            } catch (error) {
              console.error('Failed to enable auto-merge:', error);
              throw error;
            }
