---
name: Auto-merge Dependabot PRs

"on":
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        # v2.1.4
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42
        with:
          appId: ${{ secrets.APP_ID }}
          privateKey: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Enable auto-merge for Dependabot PRs
        # v7.0.1
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            try {
              await github.rest.pulls.enableAutoMerge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                merge_method: 'squash'
              });

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: '🤖 Auto-merge enabled. This PR will merge automatically once all required checks pass.'
              });

              console.log('Auto-merge enabled successfully');
            } catch (error) {
              console.error('Failed to enable auto-merge:', error);
              throw error;
            }
